language: python
python:
 - "2.7"
env:
 - DJANGO_VERSION=1.4.16
 - DJANGO_VERSION=1.5.11
 - DJANGO_VERSION=1.6.8
 - DJANGO_VERSION=1.7.1
install:
 - pip install -q Django==$DJANGO_VERSION
script:
 - DJANGO_SETTINGS_MODULE=test_app.settings PYTHONPATH=. django-admin.py test -v 2
